image: alpine/latest
arch: x86_64
packages:
  - go
sources:
  - https://git.sr.ht/~n1c00o/svgu
artifacts:
  - svgu/testdata/dst.tar.gz
  - svgu/svgu-linux-amd64
  - svgu/svgu-linux-arm64
  - svgu/svgu-darwin-amd64
  - svgu/svgu-darwin-arm64
  - svgu/svgu-windows-amd64
  - svgu/svgu-windows-arm64
  - svgu/svgu-plan9-amd64
tasks:
  - fmt: |
      cd svgu
      gofmt -d -e -l -s cmd pkg
  - test: |
      cd svgu/testdata
      go run ../cmd/svgu/svgu.go -o=dst -v -c=DOMAINS.star
      tar -czvf dst.tar.gz dst
  - build: |
      cd svgu
      
      GOOS=linux GOARCH=amd64 go build -o svgu-linux-amd64 cmd/svgu/svgu.go
      GOOS=linux GOARCH=arm64 go build -o svgu-linux-arm64 cmd/svgu/svgu.go
      GOOS=darwin GOARCH=amd64 go build -o svgu-darwin-amd64 cmd/svgu/svgu.go
      GOOS=darwin GOARCH=arm64 go build -o svgu-darwin-arm64 cmd/svgu/svgu.go
      GOOS=windows GOARCH=amd64 go build -o svgu-windows-amd64 cmd/svgu/svgu.go
      GOOS=windows GOARCH=arm64 go build -o svgu-windows-arm64 cmd/svgu/svgu.go
      GOOS=plan9 GOARCH=amd64 go build -o svgu-plan9-amd64 cmd/svgu/svgu.go
triggers:
  - action: email
    condition: always
    to: "~n1c00o/svgu@lists.sr.ht"