image: freebsd/latest
arch: amd64
packages:
  - go
sources:
  - https://git.sr.ht/~n1c00o/svgu
artifacts:
  - svgu/testdata/dst.tar.gz
  - svgu/svgu-freebsd-amd64
  - svgu/svgu-freebsd-arm64
  - svgu/svgu-freebsd-riscv64
  - svgu/svgu-openbsd-amd64
  - svgu/svgu-openbsd-arm64
  - svgu/svgu-netbsd-amd64
  - svgu/svgu-netbsd-arm64
  - svgu/svgu-solaris-amd64
  - svgu/svgu-dragonfly-amd64
tasks:
  - fmt: |
      cd svgu
      gofmt -d -e -l -s cmd pkg
  - test: |
      cd svgu/testdata
      go run ../cmd/svgu/svgu.go -o=dst -v -c=DOMAINS.star
      tar -czvf dst.tar.gz dst
  - build: |
      cd svgu
      
      GOOS=freebsd GOARCH=amd64 go build -o svgu-freebsd-amd64 cmd/svgu/svgu.go
      GOOS=freebsd GOARCH=arm64 go build -o svgu-freebsd-arm64 cmd/svgu/svgu.go
      GOOS=freebsd GOARCH=riscv64 go build -o svgu-freebsd-riscv64 cmd/svgu/svgu.go
      GOOS=openbsd GOARCH=amd64 go build -o svgu-openbsd-amd64 cmd/svgu/svgu.go
      GOOS=openbsd GOARCH=arm64 go build -o svgu-openbsd-arm64 cmd/svgu/svgu.go
      GOOS=netbsd GOARCH=amd64 go build -o svgu-netbsd-amd64 cmd/svgu/svgu.go
      GOOS=netbsd GOARCH=arm64 go build -o svgu-netbsd-arm64 cmd/svgu/svgu.go
      GOOS=solaris GOARCH=amd64 go build -o svgu-solaris-amd64 cmd/svgu/svgu.go  
      GOOS=dragonfly GOARCH=amd64 go build -o svgu-dragonfly-amd64 cmd/svgu/svgu.go
triggers:
  - action: email
    condition: always
    to: "~n1c00o/svgu@lists.sr.ht"